### ISSUE TITLE
Clothing Names

### ISSUE THREAD

**Issue by TalkingCactus** [Tk420634/A.R.F.S.-Dallus-Ship#9]
Noticed a stack of clothing in the ~~captain's office (I think)~~ command desk, most of them seem to be using placeholder or misspelled names.
![screenshot](http://image.prntscr.com/image/a799aa34f9ed41bd929962331d38ce97.png)

**Comment by TalkingCactus** [comment]
bump

**Comment by ghost** [comment]
@thingpony

**Comment by thingpony** [comment]
Yeaaaaah. I've just been ignoring it

**Comment by cebutris** [comment]
fixed with #81

**Comment by Tk420634** [comment]
awoo
