### ISSUE TITLE
CANDY CORN HAS NO SPRITE

### ISSUE THREAD

**Issue by ghost** [Tk420634/A.R.F.S.-Dallus-Ship#92]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

0/10 NOT VISUALLY IMPRESSIVE AT ALL - IGN

**Comment by cebutris** [comment]
THIS IS THE BIGGEST ISSUE EVER PLEASE FIX. -1/10 MY IMMERSIONS BROKE SO HARD I _DIED_
